### ISSUE TITLE
Update to newest version

### ISSUE THREAD

**Issue by luka-zet** [ownport/docker-documize#2]
Please update to newest (3.1.1) version.

**Comment by ownport** [comment]
Done, new version is available to download via github or docker hub

**Comment by luka-zet** [comment]
Does not work - error while connecting to database:

```
Configuration source: flags/environment
Unable to connect to database
dial tcp 172.28.0.2:3306: connect: connection refused
goroutine 1 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc000020730, 0x0, 0xcc4cfc, 0x1d, 0xea1140, 0xc0003c0000)
	src/github.com/documize/community/edition/logging/logger.go:56 +0x128
github.com/documize/community/edition/boot.InitRuntime(0xc0000c6dc0, 0xc0000c6f00, 0x27)
	src/github.com/documize/community/edition/boot/runtime.go:92 +0x478
main.main()
	src/github.com/documize/community/edition/community.go:62 +0x4ca
database connection string format is 'username:password@tcp(host:3306)/database'
```

**Comment by luka-zet** [comment]
Sollution is adding 

```
skip-networking = 0
skip-bind-address
```
to my.cnf in MariaDB config

**Comment by ownport** [comment]
@faust86 just add next lines to docker compose.yaml for documize-server
```
    environment:
      DOCUMIZEDB: "documize:documize@tcp(mariadb-server:3306)/documize"
```
https://github.com/ownport/docker-documize/blob/master/docker-compose.yaml
